NumPy — библиотека с открытым исходным кодом для языка программирования Python. Возможности:

поддержка многомерных массивов (включая матрицы);
поддержка высокоуровневых математических функций, предназначенных для работы с многомерными массивами.

In [31]:
import numpy as np 
# help(np.array)
a = np.array([1,2,4])
print(a)

#Все элементы массива должны иметь одинаковый тип
a = np.array([1,2,'4',True])
print(a)
# тип данных будет преобразовываться автоматически
a[2] = 6.43
print(a)
# можно заполнить массив элементами другого массива копировав их
a = a[[1,1,3,1,1,1,1,3,1]]
print(a)
# возможно создавать массивы на основе логических операций 
a = a[[True,True,False,True,True,True,True,True,True]]
print(a)
""" Метод reshape позволяет создать новый массив с произвольным количеством строк
и столбцов"""
b = a.reshape(4,2)
print(b)

[1 2 4]
['1' '2' '4' 'True']
['1' '2' '6.43' 'True']
['2' '2' 'True' '2' '2' '2' '2' 'True' '2']
['2' '2' '2' '2' '2' '2' 'True' '2']
[['2' '2']
 ['2' '2']
 ['2' '2']
 ['True' '2']]


In [42]:
# Способы формирования массивов 

#просто перечислить элементы 
a = np.array([1,2,3,4])
a = np.array([1,2,3,4],'float')
print(a)
a = np.array([1,2,3,400],dtype='uint32')
print(a)
a = np.int8(a)
print(a)

[1. 2. 3. 4.]
[  1   2   3 400]
[   1    2    3 -112]


In [53]:
# первый элемент может быть либо списком либо кортежем 
a = np.array('hello')
a = np.array([[2,4],[4,6],[6,8]])
print(a)
b = np.array([[a*2],[a*3],[a*4]])
print('b=', b)
print('b=', b[0])

[[2 4]
 [4 6]
 [6 8]]
b= [[[[ 4  8]
   [ 8 12]
   [12 16]]]


 [[[ 6 12]
   [12 18]
   [18 24]]]


 [[[ 8 16]
   [16 24]
   [24 32]]]]
b= [[[ 4  8]
  [ 8 12]
  [12 16]]]


In [76]:
# Способы создания массивов
a = np.array([1]*10)
print(a)
# возможно использовать механизм генерации списков 
a = np.array([i*2 for i in range(12)])
print(a)
# Создать массив заполненный случайно 
a = np.empty(34, 'int16')
print(a)
# Создает матрице m  на n  c  единицами на "диагонали"
a = np.eye(4,4,-1,'int')
print(a)
# создает диагональную матрицы размерности n
a = np.identity(12)
print(a)
# заполнить нулями или единицами или конкретными значениями
a = np.ones(125)
a = np.zeros(62)
a = np.full(62, 666)
print(a)

[1 1 1 1 1 1 1 1 1 1]
[ 0  2  4  6  8 10 12 14 16 18 20 22]
[27776  9709 21857     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0]
[[0 0 0 0]
 [1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
[666 666 666 666 666 666 666 666 666 666 666 666 666 666 666 666 666 666
 666 666 666 666 666 666 666 666 666 666 666 666 666 666 666 666 666 666
 666 666 666 666 666 666 666 666 666 666 666 666 666 666 666 666 666 666

In [136]:
# создает матрицу
a = np.mat([(1,2,3), (4,5,6)])
a = np.mat('1 2 3 4 5')
a = np.mat('1,2,3,4,5')
a = np.mat('1,2; 4,5')
print(a)
print('___________')
# создает диагональную матрицу
a = np.diag([1,2,3,4])
print(a)
# или возвращает главную даигональ
a = np.diag([(8,2,3), (4,8,6), (7,8,8)])
print(a)
# можно создать даигональную матрицу из списка 
a = np.diagflat([(8,2,3), (4,8,6), (7,8,8)])
print(a)
# треуголную матрицу можно создать так
a = np.tri(4,4)
print(a)
# или привести матрицу к диагональному виду 
a = np.tril(a.transpose())
print(a)
# можно сделать обратную диагональную матрицу 
a = np.mat([[3]*3,[3]*3,[3]*3])
a = np.triu(a)
print(a)

[[1 2]
 [4 5]]
___________
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
[8 8 8]
[[8 0 0 0 0 0 0 0 0]
 [0 2 0 0 0 0 0 0 0]
 [0 0 3 0 0 0 0 0 0]
 [0 0 0 4 0 0 0 0 0]
 [0 0 0 0 8 0 0 0 0]
 [0 0 0 0 0 6 0 0 0]
 [0 0 0 0 0 0 7 0 0]
 [0 0 0 0 0 0 0 8 0]
 [0 0 0 0 0 0 0 0 8]]
[[1. 0. 0. 0.]
 [1. 1. 0. 0.]
 [1. 1. 1. 0.]
 [1. 1. 1. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[3 3 3]
 [0 3 3]
 [0 0 3]]


In [135]:
# формирование числовых диапазонов 
a = np.arange(4)
print(a)
a = np.arange(0,np.pi,0.1)
print(a)
#Линейная прогрессия 
a= np.linspace(0,np.pi*2,100)
print(a)
#логарифмическая
a= np.logspace(7,18,12)
print(a)
#геометрическая
a= np.geomspace(7,18,12)
print(a)
# Можно создать копию массива
b = np.copy(a)

[0 1 2 3]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7
 1.8 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.  3.1]
[0.         0.06346652 0.12693304 0.19039955 0.25386607 0.31733259
 0.38079911 0.44426563 0.50773215 0.57119866 0.63466518 0.6981317
 0.76159822 0.82506474 0.88853126 0.95199777 1.01546429 1.07893081
 1.14239733 1.20586385 1.26933037 1.33279688 1.3962634  1.45972992
 1.52319644 1.58666296 1.65012947 1.71359599 1.77706251 1.84052903
 1.90399555 1.96746207 2.03092858 2.0943951  2.15786162 2.22132814
 2.28479466 2.34826118 2.41172769 2.47519421 2.53866073 2.60212725
 2.66559377 2.72906028 2.7925268  2.85599332 2.91945984 2.98292636
 3.04639288 3.10985939 3.17332591 3.23679243 3.30025895 3.36372547
 3.42719199 3.4906585  3.55412502 3.61759154 3.68105806 3.74452458
 3.8079911  3.87145761 3.93492413 3.99839065 4.06185717 4.12532369
 4.1887902  4.25225672 4.31572324 4.37918976 4.44265628 4.5061228
 4.56958931 4.63305583 4.69652235 4.75998887 4.82345539 4

In [153]:
a = np.fromiter('hello', dtype ='<U1')
print(a)
a= np.fromstring('1 2 3 ', dtype = 'int8', sep=' ')
print(a)

['h' 'e' 'l' 'l' 'o']
[1 2 3]
